# User model constants
USER_NAME_MAX_LEN = 124
USER_SURNAME_MAX_LEN = 124
USER_PHONE_MAX_LEN = 12
USER_ABOUT_MAX_LEN = 256

# Project model constants
PROJECT_NAME_MAX_LEN = 200
PROJECT_STATUS_MAX_LEN = 6
